from frontend.theme import html, COMPANY_URL, CONTACT_EMAIL, page_footer, page_header, page_hero

page_header("about")
page_hero(
    "About <span class='vl-purple-text'>Leaf Disease</span> <span class='vl-green-text'>AI</span>",
    "Applied AI from Vibrant Logics to help growers spot plant disease early.",
)

html(
    f"""
    <div class="vl-prose">
        <h2>What it does</h2>
        <p>Leaf Disease AI analyzes a photo of a plant leaf and tells you whether it looks
        healthy or diseased. When it finds a problem, it names the likely disease and its
        category (fungal, bacterial, viral, pest or nutrient deficiency), estimates severity,
        lists the visible symptoms and probable causes, and suggests treatment steps.</p>

        <h2>How it works</h2>
        <p>Your image is sent to a state-of-the-art vision language model that has been
        instructed to act as a plant pathology assistant. The model first checks that the
        photo actually shows a plant leaf, then returns a structured diagnosis that we
        present in a clear, readable format. Results usually arrive within a few seconds.</p>

        <h2>Who it's for</h2>
        <ul>
            <li>Farmers and growers who want a fast first opinion in the field</li>
            <li>Home gardeners troubleshooting a struggling plant</li>
            <li>Agronomists and agri-businesses looking to triage cases at scale</li>
        </ul>

        <div class="vl-callout">
            <b>Please note:</b> diagnoses are generated by AI and can be wrong. Use them as a
            starting point, and consult a qualified agronomist or plant pathologist before
            making decisions about high-value crops or chemical treatments.
        </div>

        <h2>About Vibrant Logics</h2>
        <p>Vibrant Logics is a next-generation software development company focused on
        delivering innovative digital solutions. We collaborate closely with our clients,
        innovate with modern technology, and build scalable products that drive real
        business results, from custom software and cloud platforms to applied AI like
        this tool.</p>
        <p>Want something similar for your organisation? Visit
        <a href="{COMPANY_URL}" target="_blank">vibrantlogics.com</a> or email
        <a href="mailto:{CONTACT_EMAIL}">{CONTACT_EMAIL}</a>.</p>
    </div>
    """,
)

page_footer()
